# git
alias gb='git branch'
alias gba='git branch -a'
alias gc='git commit -a -v'
alias gd='git diff | less'
alias gl='git pull'
alias gp='git push'
alias gst='git status'
alias ga='git add'
alias sgl='git svn rebase'
alias sgp='git svn dcommit'
